name: Test
on:
  pull_request: null
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "${{ secrets.REGISTRY }}"
